services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - estoque-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - estoque-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-produtos:
    build: ./api-produtos
    container_name: api-produtos
    restart: always
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - estoque-net

  api-estoque:
    build: ./api-estoque
    container_name: api-estoque
    restart: always
    ports:
      - "5002:5002"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
      API_PRODUTOS_URL: http://api-produtos:5001
    depends_on:
      mysql-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      api-produtos:
        condition: service_started
    networks:
      - estoque-net

  api-movimentacoes:
    build: ./api-movimentacoes
    container_name: api-movimentacoes
    restart: always
    ports:
      - "5003:5003"
    environment:
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
      API_ESTOQUE_URL: http://api-estoque:5002
      API_PRODUTOS_URL: http://api-produtos:5001
    depends_on:
      mongo-db:
        condition: service_healthy
      api-estoque:
        condition: service_started
    networks:
      - estoque-net

networks:
  estoque-net:
    driver: bridge

volumes:
  mysql-data:
  mongo-data: